name: cos424-hw2
channels:
  - https://conda.anaconda.org/menpo
  - conda-forge
dependencies:
  - python==3.6
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - scikit-learn
  - scipy
  - h5py
  - pip:
    - argparse
    - fancyimpute
    - tqdm
